### ISSUE TITLE
[Improving the Accessibility of Your Website] rewrite to fix flow with new plan

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-implementation#53]
This is a comment related to the page [Improving the Accessibility of Your Website](//w3c.github.io/wai-planning-and-implementation/improving.html)

I think a couple years ago when we worked on this resource, it was thought that the bits might be integrated into a broader resource, e.g., _dynamic_ planning guide. Thus Kevin re-wrote it with the "key action" chunks to be used elsewhere. Several months ago we determined that this will be a stand-alone resource.

As such, it needs a rewrite to fix the flow. For example, the flow of the "Determine scope and target" section is:
- paragraph 1: define scope, define target
- 2: comment about scope, comment about target
- 3: comment about scope
- key 1: about target - but doesn't say "target" in mini-header
- key 2: about scope - but doesn't say "scope" in mini-header

It would be better to talk about scope (include the key action), then talk about target (include the key action).

Throughout, probably it would be best not to group the "key actions" and get rid of that heading -- since that is messing up the flow. Possibly use the term in-line (along the lines of [these "User Needs"](http://w3c.github.io/low-vision-a11y-tf/requirements.html#font) - but prettier ;-) -- although I'm not sure that would be helpful.

Another example: I think the flow of the previous version's "[Prioritizing the Repairs](https://www.w3.org/WAI/EO/Drafts/Improving2012.html#prior)" section flows much better than this "[Prioritize solutions](http://w3c.github.io/wai-planning-and-implementation/improving#prioritize)" section.

**Comment by iadawn** [comment]
Made a fair few edits through the page. I think the flow from the previous section has a bit of a problem in it, which I tried to address. You can prioritize by barrier or area but in both cases you really need to know what is the impact on users and what resources are required to fix it.

So the flow I adopted was to pose the two key questions and then provide the two approaches to using the information. In reality, it is likely that a mix of both prioritization approaches would be adopted, which is why I have avoided making them look like either/ors.
