### ISSUE TITLE
[Improving] “Understanding the basics”

### ISSUE THREAD

**Issue by yatil** [w3c/wai-planning-and-implementation#70]
[this is minor and not to block publication. editor’s discretion, feel free to close “wontfix” if you disagree.]

While I understand that we want to give people background information, I think for interim repairs the last thing I wanted to read is basics. I’d want the direct advice to my problem. Give me the basics later.

I propose to

a. Remove the section altogether _or_
b. Move the section before the “Longer Term: Sustainable Plan” section.

**Comment by bakkenb** [comment]
[mild-medium] maybe this is not an issue as I see it. Don't want to stop approval.

I had the exact same feeling as @yatil when I read this. I was thinking, "okay, when they click those links, they will see a plethora of other links and then you've just lost them." Those pages have too many other rabbit trails to go down. The info is good and important, but too easy to get lost in. They are here for a quick fix and this will push them back into learning a lot about accessibility. Some will take it, but others will tune out of the document altogether.

It is good information, so I would vote for moving it down to the longer term area. It could also then be replaced with something that does give a quick overview of web accessibility without a lot of links to all the other resources, kind of a primer page. Maybe that is not even needed as Eric states.

**Comment by nitedog** [comment]
Just to channel @iadawn who had very similar concerns.

**Comment by shawna-slh** [comment]
This is a hard one. If someone has no idea what accessibility is all about, can they at all manage reasonable fixes? /me thinks not...

I'm imagining someone comes to me asking for advice with, "Help! I've got to fix accessibility and I don't have a clue?!?"... I _would_ tell them to at least _skim_ those two pages -- not follow all the links, but at least give it a quick read through.

Maybe we should try saying something like that before the links?

**Comment by yatil** [comment]
Hm. I don’t find the second link very skimmable. It just turns the noise:signal ratio up a lot. I’d strongly prefer three paragraphs of text here with a link to “mored detail”  instead of pointing users at the wall of text that is especially the principles page.

As noted above, I don’t feel strongly about that issue and it is editor’s discretion. I just wanted to voice my discomfort that some people might just be overwhelmed by a resource that is supposed to help as a “first aid”. A first aid kit from the real world is also not giving you all the background to how wounds work, when you unpack it, but it instead immediately leads you to the tools you need.

**Comment by nitedog** [comment]
As compromise, the following changes were made:
1. Moved key resources (Getting Started Tips, Tutorials, and QuickRef) to the top of the page as to a new section prominently titled "Important Resources" -- this is where to get immediate help.
2. Removed the second link (was "Accessibility Principles" from "How People with Disabilities Use the Web") from the list to a separate paragraph with the wording "If there is a need, more in-depth introduction...".
3. Rephrased the section and added wording "If you are new to accessibility..." before the list, so that people who do not need this information are encouraged to skip it.
4. Added "Web Accessibility Perspectives" videos to the list, as it may be essential background depending on the situation.

Hope this addresses all comments so far! Re-open issue if it doesn't. Ping @yatil @bakkenb @slhenry

**Comment by bakkenb** [comment]
Yes, I like these changes at first glance. Will be doing a thorough review with EOWG next week.
